import bcrypt from "bcryptjs"
const data = {
  users: [
    {
      name: 'midatou',
      email: 'midouchecha@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
     
      name: 'shirt x',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'celio',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
     
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
     
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
    
      name: 'white shirt',
      category: 'shirts',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'lcw',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
     
      name: 'lcw shirt',
      category: 'shirts',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'lcw',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      
      name: 'Adidas Fit t-shirt',
      category: 't-shirts',
      image: '/images/p6.jpg',
      price: 39,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'jeans jacket',
      category: 'jacket',
      image: '/images/p7.jpg',
      price: 110,
      countInStock: 12,
      brand: 'lee cooper',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'jeans jacket rock',
      category: 'jacket',
      image: '/images/p9.jpg',
      price: 120,
      countInStock: 12,
      brand: 'lee cooper',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'l Fit t-shirt',
      category: 't-shirts',
      image: '/images/p9.jpg',
      price: 89,
      countInStock: 12,
      brand: 'polo',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'calvin Fit t-shirt',
      category: 't-shirts',
      image: '/images/p10.jpg',
      price: 59,
      countInStock: 12,
      brand: 'calvin clein',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'paul&bear t-shirt',
      category: 't-shirts',
      image: '/images/p11.jpg',
      price: 49,
      countInStock: 12,
      brand: 'paul&bear',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'blue sky jacket',
      category: 'jacket',
      image: '/images/p12.jpg',
      price: 89,
      countInStock: 12,
      brand: 'lee cooper',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'black pant',
      category: 'pants',
      image: '/images/p13.jpg',
      price: 75,
      countInStock: 12,
      brand: 'tommy',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'levis jean pant',
      category: 'pants',
      image: '/images/p14.jpg',
      price: 119,
      countInStock: 12,
      brand: 'levis',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
    
      name: 'levis jean pant',
      category: 'pants',
      image: '/images/p15.jpg',
      price: 89,
      countInStock: 12,
      brand: 'levis',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      
      name: 'black soard pant',
      category: 'pants',
      image: '/images/p16.jpg',
      price: 99,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
     
      name: 'jeans pant',
      category: 'pants',
      image: '/images/p17.jpg',
      price: 99,
      countInStock: 90,
      brand: 'tommy',
      rating: 4.5,
      numReviews: 25,
      description: 'high quality product',
    },
    {
      
      name: 'jackson jeans',
      category: 'pants',
      image: '/images/p18.jpg',
      price: 79,
      countInStock: 90,
      brand: 'levis',
      rating: 4.5,
      numReviews: 39,
      description: 'high quality product',
    },
    {
      
      name: 'jeans 2021',
      category: 'pants',
      image: '/images/p19.jpg',
      price: 89,
      countInStock: 44,
      brand: 'lee cooper',
      rating: 4.5,
      numReviews: 72,
      description: 'high quality product',
    },
    {
      
      name: 'black formal',
      category: 'costumes',
      image: '/images/p20.jpg',
      price: 480,
      countInStock: 17,
      brand: 'armani',
      rating: 4.5,
      numReviews: 29,
      description: 'high quality product',
    },
    {
      
      name: 'blue sky formal',
      category: 'costumes',
      image: '/images/p21.jpg',
      price: 480,
      countInStock: 32,
      brand: 'armani',
      rating: 4.4,
      numReviews: 19,
      description: 'high quality product',
    },
    {
     
      name: 'white formal',
      category: 'costumes',
      image: '/images/p22.jpg',
      price: 500,
      countInStock: 53,
      brand: 'armani',
      rating: 4.5,
      numReviews: 13,
      description: 'high quality product',
    },
    {
      
      name: 'Nike carbon',
      category: 'shoes',
      image: '/images/p23.jpg',
      price: 235,
      countInStock: 12,
      brand: 'Nike',
      rating: 4,
      numReviews: 19,
      description: 'high quality product',
    },
    {
     
      name: 'Adidas purple',
      category: 'shoes',
      image: '/images/p24.jpg',
      price: 199,
      countInStock: 18,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 9,
      description: 'high quality product',
    },
    {
      
      name: 'Nike volcano',
      category: 'shoes',
      image: '/images/p25.jpg',
      price: 139,
      countInStock: 150,
      brand: 'nike',
      rating: 4.5,
      numReviews: 68,
      description: 'high quality product',
    },
    {
     
      name: 'B12 Adidas',
      category: 'shoes',
      image: '/images/p26.jpg',
      price: 99,
      countInStock: 22,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 31,
      description: 'high quality product',
    },
    {
     
      name: 'B13 Adidas',
      category: 'shoes',
      image: '/images/p27.jpg',
      price: 99,
      countInStock: 22,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 31,
      description: 'high quality product',
    },
    {
      
      name: 'Sun rise Adidas',
      category: 'shoes',
      image: '/images/p28.jpg',
      price: 99,
      countInStock: 22,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 31,
      description: 'high quality product',
    }

  ],
};
export default data;
